# syntax=docker/dockerfile:1.4
# One-time (or rare) build for the shared conda environment image.
# Build and tag this image once, then regular worker deploys reuse it.

FROM ubuntu:22.04 AS base

WORKDIR /app

ENV DEBIAN_FRONTEND=noninteractive \
    PYTHONUNBUFFERED=1 \
    PATH="/opt/conda/bin:$PATH"

RUN apt-get update && apt-get install -y --no-install-recommends \
        build-essential \
        curl \
        wget \
        libgomp1 \
        python3 \
        python3-pip \
        python3-dev \
    && rm -rf /var/lib/apt/lists/*

RUN wget -q https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh \
        -O /tmp/miniconda.sh \
    && bash /tmp/miniconda.sh -b -p /opt/conda \
    && rm /tmp/miniconda.sh \
    && /opt/conda/bin/conda config --set always_yes yes \
    && /opt/conda/bin/conda config --add channels conda-forge \
    && /opt/conda/bin/conda config --set channel_priority strict \
    && /opt/conda/bin/conda tos accept --channel https://repo.anaconda.com/pkgs/main \
    && /opt/conda/bin/conda tos accept --channel https://repo.anaconda.com/pkgs/r \
    && /opt/conda/bin/conda install -n base -c conda-forge mamba -y \
    && /opt/conda/bin/conda clean -afy

FROM base AS env-kinform
COPY docker-requirements/kinform_requirements.txt ./docker-requirements/
RUN --mount=type=cache,target=/opt/conda/pkgs,sharing=locked \
    --mount=type=cache,id=webkinpred-pip-py312,target=/root/.cache/pip,sharing=locked \
    mamba create -n kinform_env python=3.12 -c conda-forge -y \
    && conda run -n kinform_env pip install -r docker-requirements/kinform_requirements.txt

FROM base AS env-dlkcat
COPY docker-requirements/dlkcat_requirements.txt ./docker-requirements/
RUN --mount=type=cache,target=/opt/conda/pkgs,sharing=locked \
    --mount=type=cache,id=webkinpred-pip-py37,target=/root/.cache/pip,sharing=locked \
    mamba create -n dlkcat_env python=3.7.12 -c conda-forge -y \
    && mamba install -n dlkcat_env -c conda-forge --override-channels rdkit=2020.09.1 -y \
    && conda run -n dlkcat_env pip install -r docker-requirements/dlkcat_requirements.txt

FROM base AS env-eitlem
COPY docker-requirements/eitlem_requirements.txt ./docker-requirements/
RUN --mount=type=cache,target=/opt/conda/pkgs,sharing=locked \
    --mount=type=cache,id=webkinpred-pip-py310,target=/root/.cache/pip,sharing=locked \
    mamba create -n eitlem_env python=3.10.15 -c conda-forge -y \
    && conda run -n eitlem_env pip install -r docker-requirements/eitlem_requirements.txt

FROM base AS env-turnup
COPY docker-requirements/turnup_requirements.txt ./docker-requirements/
RUN --mount=type=cache,target=/opt/conda/pkgs,sharing=locked \
    --mount=type=cache,id=webkinpred-pip-py37,target=/root/.cache/pip,sharing=locked \
    mamba create -n turnup_env python=3.7 -c conda-forge -y \
    && mamba install -n turnup_env -c conda-forge py-xgboost=1.6.1 -y \
    && conda run -n turnup_env pip install -r docker-requirements/turnup_requirements.txt

FROM base AS env-unikp
COPY docker-requirements/unikp_requirements.txt ./docker-requirements/
RUN --mount=type=cache,target=/opt/conda/pkgs,sharing=locked \
    --mount=type=cache,id=webkinpred-pip-py37,target=/root/.cache/pip,sharing=locked \
    mamba create -n unikp python=3.7.12 -c conda-forge -y \
    && conda run -n unikp pip install -r docker-requirements/unikp_requirements.txt \
    && conda run -n unikp pip install accelerate

FROM base AS env-catapro
COPY docker-requirements/catapro_requirements.txt ./docker-requirements/
RUN --mount=type=cache,target=/opt/conda/pkgs,sharing=locked \
    --mount=type=cache,id=webkinpred-pip-py310,target=/root/.cache/pip,sharing=locked \
    mamba create -n catapro_env python=3.10.15 -c conda-forge -y \
    && mamba install -n catapro_env -c conda-forge rdkit=2024.03.6 -y \
    && conda run -n catapro_env pip install -r docker-requirements/catapro_requirements.txt

FROM base AS env-catpred
COPY docker-requirements/catpred_requirements.txt ./docker-requirements/
RUN --mount=type=cache,target=/opt/conda/pkgs,sharing=locked \
    --mount=type=cache,id=webkinpred-pip-py310,target=/root/.cache/pip,sharing=locked \
    mamba create -n catpred_env python=3.10.15 -c conda-forge -y \
    && mamba install -n catpred_env -c conda-forge rdkit=2024.03.6 -y \
    && conda run -n catpred_env pip install -r docker-requirements/catpred_requirements.txt

FROM base AS env-mmisakm
COPY docker-requirements/mmisakm_requirements.txt ./docker-requirements/
RUN --mount=type=cache,target=/opt/conda/pkgs,sharing=locked \
    --mount=type=cache,id=webkinpred-pip-py39,target=/root/.cache/pip,sharing=locked \
    mamba create -n mmisakm_env python=3.9 -c conda-forge -y \
    && conda run -n mmisakm_env pip install -r docker-requirements/mmisakm_requirements.txt


FROM base AS env-omniesi
COPY docker-requirements/omniesi_requirements.txt ./docker-requirements/
RUN --mount=type=cache,target=/opt/conda/pkgs,sharing=locked \
    --mount=type=cache,id=webkinpred-pip-py38,target=/root/.cache/pip,sharing=locked \
    mamba create -n omniesi_env python=3.8 -c conda-forge -y \
    && conda run -n omniesi_env pip install -r docker-requirements/omniesi_requirements.txt

FROM base AS env-iecata
COPY docker-requirements/iecata_requirements.txt ./docker-requirements/
RUN --mount=type=cache,target=/opt/conda/pkgs,sharing=locked \
    --mount=type=cache,id=webkinpred-pip-iecata,target=/root/.cache/pip,sharing=locked \
    mamba create -n iecata_env python=3.8 \
    && conda run -n iecata_env pip install \
        -r docker-requirements/iecata_requirements.txt

FROM base AS env-realkcat
COPY docker-requirements/realkcat_requirements.txt ./docker-requirements/
RUN --mount=type=cache,target=/opt/conda/pkgs,sharing=locked \
    --mount=type=cache,id=webkinpred-pip-py312,target=/root/.cache/pip,sharing=locked \
    mamba create -n realkcat_env python=3.9 -c conda-forge -y \
    && conda run -n realkcat_env pip install -r docker-requirements/realkcat_requirements.txt

FROM base AS env-catrange
COPY docker-requirements/catrange_requirements.txt ./docker-requirements/
RUN --mount=type=cache,target=/opt/conda/pkgs,sharing=locked \
    --mount=type=cache,id=webkinpred-pip-py310,target=/root/.cache/pip,sharing=locked \
    mamba create -n catrange_env python=3.10 -c conda-forge -y \
    && conda run -n catrange_env pip install -r docker-requirements/catrange_requirements.txt

FROM base AS env-pseq2sites
RUN --mount=type=cache,target=/opt/conda/pkgs,sharing=locked \
    --mount=type=cache,id=webkinpred-pip-py37,target=/root/.cache/pip,sharing=locked \
    mamba create -n pseq2sites python=3.7.12 -c conda-forge -y \
    && conda run -n pseq2sites pip install --prefer-binary \
        torch==1.7.1 numpy==1.20.0 transformers==4.30.2 sentencepiece==0.2.0 \
        biopython==1.79 rdkit-pypi==2021.3.1 openbabel-wheel pandas tqdm

FROM base AS env-esm
RUN --mount=type=cache,target=/opt/conda/pkgs,sharing=locked \
    --mount=type=cache,id=webkinpred-pip-py37,target=/root/.cache/pip,sharing=locked \
    mamba create -n esm python=3.7 -c conda-forge -y \
    && conda run -n esm pip install torch fair-esm pandas tqdm

FROM base AS env-esmc
RUN --mount=type=cache,target=/opt/conda/pkgs,sharing=locked \
    --mount=type=cache,id=webkinpred-pip-py312,target=/root/.cache/pip,sharing=locked \
    mamba create -n esmc python=3.12 -c conda-forge -y \
    && conda run -n esmc pip install esm pandas tqdm

FROM base AS env-prot-t5
RUN --mount=type=cache,target=/opt/conda/pkgs,sharing=locked \
    --mount=type=cache,id=webkinpred-pip-py39,target=/root/.cache/pip,sharing=locked \
    mamba create -n prot_t5 python=3.9 -c conda-forge -y \
    && conda run -n prot_t5 pip install \
        torch transformers sentencepiece pandas tqdm accelerate

FROM base AS env-mmseqs2
RUN --mount=type=cache,target=/opt/conda/pkgs,sharing=locked \
    mamba create -n mmseqs2_env python=3.10 -c conda-forge -y \
    && mamba install -n mmseqs2_env -c bioconda mmseqs2=13.45111 -y

FROM base AS final

COPY --from=env-kinform    /opt/conda/envs/kinform_env   /opt/conda/envs/kinform_env
COPY --from=env-dlkcat     /opt/conda/envs/dlkcat_env    /opt/conda/envs/dlkcat_env
COPY --from=env-eitlem     /opt/conda/envs/eitlem_env    /opt/conda/envs/eitlem_env
COPY --from=env-turnup     /opt/conda/envs/turnup_env    /opt/conda/envs/turnup_env
COPY --from=env-unikp      /opt/conda/envs/unikp         /opt/conda/envs/unikp
COPY --from=env-catapro    /opt/conda/envs/catapro_env   /opt/conda/envs/catapro_env
COPY --from=env-catpred    /opt/conda/envs/catpred_env   /opt/conda/envs/catpred_env
COPY --from=env-mmisakm   /opt/conda/envs/mmisakm_env  /opt/conda/envs/mmisakm_env
COPY --from=env-omniesi   /opt/conda/envs/omniesi_env  /opt/conda/envs/omniesi_env
COPY --from=env-iecata    /opt/conda/envs/iecata_env   /opt/conda/envs/iecata_env
COPY --from=env-realkcat   /opt/conda/envs/realkcat_env  /opt/conda/envs/realkcat_env
COPY --from=env-catrange   /opt/conda/envs/catrange_env /opt/conda/envs/catrange_env
COPY --from=env-pseq2sites /opt/conda/envs/pseq2sites    /opt/conda/envs/pseq2sites
COPY --from=env-esm        /opt/conda/envs/esm           /opt/conda/envs/esm
COPY --from=env-esmc       /opt/conda/envs/esmc          /opt/conda/envs/esmc
COPY --from=env-prot-t5    /opt/conda/envs/prot_t5       /opt/conda/envs/prot_t5
COPY --from=env-mmseqs2    /opt/conda/envs/mmseqs2_env   /opt/conda/envs/mmseqs2_env

RUN find /opt/conda -name "*.pyc" -delete \
    && find /opt/conda -name "__pycache__" -type d -exec rm -rf {} + 2>/dev/null || true
