# Generated by Django 5.1.3 on 2024-11-20 13:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                ("job_id", models.AutoField(primary_key=True, serialize=False)),
                ("prediction_type", models.CharField(max_length=10)),
                ("kcat_method", models.CharField(blank=True, max_length=50, null=True)),
                ("km_method", models.CharField(blank=True, max_length=50, null=True)),
                ("status", models.CharField(max_length=20)),
                (
                    "submission_time",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("completion_time", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                (
                    "output_file",
                    models.FileField(blank=True, null=True, upload_to="jobs/%Y/%m/%d/"),
                ),
                ("total_molecules", models.IntegerField(default=0)),
                ("molecules_processed", models.IntegerField(default=0)),
                ("invalid_molecules", models.IntegerField(default=0)),
                ("total_predictions", models.IntegerField(default=0)),
                ("predictions_made", models.IntegerField(default=0)),
            ],
        ),
    ]
