# Generated by Django 5.1.3 on 2025-04-02 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="estimated_duration",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="job",
            name="priority",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="job",
            name="resource_requirements",
            field=models.CharField(default="normal", max_length=50),
        ),
    ]
