# Generated by Django 5.1.3 on 2025-04-02 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_job_estimated_duration_job_priority_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="estimated_duration",
        ),
        migrations.RemoveField(
            model_name="job",
            name="priority",
        ),
        migrations.RemoveField(
            model_name="job",
            name="resource_requirements",
        ),
    ]
