# Generated by Django 5.1.3 on 2025-04-02 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_remove_job_estimated_duration_remove_job_priority_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="kcat_complete",
            field=models.BooleanField(default=False),
        ),
    ]
