# Generated by Django 5.1.3 on 2025-04-02 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_job_kcat_complete"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="kcat_complete",
        ),
    ]
