# Generated by Django 5.1.3 on 2025-06-07 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_remove_job_kcat_complete"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="handle_long_sequences",
            field=models.CharField(
                choices=[("truncate", "truncate"), ("skip", "skip")],
                default="truncate",
                max_length=100,
            ),
        ),
    ]
