# Generated by Django 5.1.3 on 2025-06-07 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_job_public_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="public_id",
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
