# Generated by Django 4.2.20 on 2025-06-07 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_job_public_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="public_id",
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
