# Generated by Django 5.1.3 on 2025-07-31 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_alter_job_public_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="ip_address",
            field=models.CharField(blank=True, default="", max_length=45),
        ),
        migrations.AddField(
            model_name="job",
            name="requested_rows",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
