# Generated by Django 5.1.3 on 2025-08-20 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_job_ip_address_job_requested_rows"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApiUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(unique=True)),
                (
                    "custom_daily_limit",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Custom daily limit for this IP. Leave blank to use default.",
                        null=True,
                    ),
                ),
                ("is_blocked", models.BooleanField(default=False)),
                ("first_seen", models.DateTimeField(auto_now_add=True)),
                ("last_seen", models.DateTimeField(auto_now=True)),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Admin notes about this user"
                    ),
                ),
            ],
            options={
                "verbose_name": "API User",
                "verbose_name_plural": "API Users",
                "ordering": ["-last_seen"],
            },
        ),
        migrations.AddField(
            model_name="job",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.apiuser",
            ),
        ),
    ]
